### ISSUE TITLE
correct calc_optimal_chi for dew conditions (vpd<0)

### ISSUE THREAD

**Issue by mpeaucelle** [stineb/rpmodel#2]
Hello Beni, 
I found a condition where your model crashes. On fluxnet sites, I compute VPD from Qair, press and Temperature. 
In dew conditions we can have negative vpd, with qair>qsat. 
In calc_optimal_chi you have sqrt(vpd), which leads to NaN values for vpd<0. You can easily correct that by using sqrt(max(vpd,0)).
Cheers,

**Comment by stineb** [comment]
Thanks @mpeaucelle. I followed your suggestion.
