### ISSUE TITLE
Atmospheric CO2 driver not vectorized

### ISSUE THREAD

**Issue by arthur-e** [stineb/rpmodel#3]
Unlike other inputs, if a sequence of CO2 values is provided, only the first value is used.

**Expected behavior** (this is what currently happens with, e.g., a VPD sweep):

```r
> rpmodel( tc = 25, vpd = seq(500, 3000, 500), co2 = 400, fapar = 1, ppfd = 10, elv = 0, do_soilmstress = FALSE, do_ftemp_kphio = FALSE)$gpp
[1] 2.224166 2.115682 2.035845 1.970669 1.914766 1.865385
```

**Actual behavior** (when a CO2 sweep is used instead):

```r
> rpmodel( tc = 25, vpd = 500, co2 = seq(350, 400, 10), fapar = 1, ppfd = 10, elv = 0, do_soilmstress = FALSE, do_ftemp_kphio = FALSE)$gpp
[1] 2.027605
```

**Comment by stineb** [comment]
Dear Arthur,
Thanks a lot for pointing this out.
I've looked into it and propose a bugfix as released by [this here](https://github.com/stineb/rpmodel/releases/tag/v1.1.0). Please get the latest version of the package through github (`git pull`) and check if this now runs without further issues.
Thanks
beni
